#!/bin/bash
set -e
python setup.py install
python -m abfs serve \
  --weights-s3 "$WEIGHTS_S3" \
  --weights-path "$WEIGHTS_PATH" \
  --model-s3 "$MODEL_S3" \
  --model-path "$MODEL_PATH" \
  --tolerance "${TOLERANCE:0.5}" \
  --port ${PORT:-1337} \
  --mapbox-api-key "$MAPBOX_API_KEY"
